# Read the Docs configuration file
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py
  builder: html

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

# Python configuration
python:
  version: "3.11"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs